### PR TITLE
Added my name Ravi Pandey to the setup.py file

### PR DESCRIPTION
**Pull request by RaviPandey33**
Hey i have added my name in the setup.py file. Can you please approve the change.

### CODE REVIEW

**Comment by wallscheid** [comment]
Sorry, but why should you be added to the authors list?

**Comment by RaviPandey33** [comment]
Hello. I was supposed to do this task according to my assignment in UPB . I had to create a pull request to the original repository after writing my name

**Comment by wallscheid** [comment]
I cannot imagine that the task was to add your name to the original repo, but to your individul forked one. May I ask from whom this task was given?

**Comment by RaviPandey33** [comment]
image

**Comment by wallscheid** [comment]
Where is that task from, i.e., from which course?

**Comment by RaviPandey33** [comment]
Its a task in the assignment given to us for the project group. There were many other tasks but this was one of them.
Project page : https://cs.uni-paderborn.de/studium/studienelemente/projektgruppen/#:~:text=Title%20of%20the%20PG%3A%C2%A0%20Reinforcement%20Learning%20for%20Energy%20Conversion%20Applications%20(LEARL)


image

**Comment by wkirgsn** [comment]
Hi Ravi,
thanks for your PR. You solved that part of the test perfectly and you'll get the points for that third part.
Sorry for the hassle

**Pull request closed without merging**
